### ISSUE TITLE
How extend or override style input.

### ISSUE THREAD

**Issue by mynameiskreang** [koleary94/Angular-2-Datepicker#67]
Hello, I try to extend, override component and CSS.
but it's not work.

I want to change your input style to right style.
how can I do?

![screenshot from 2017-02-01 01 18 33](https://cloud.githubusercontent.com/assets/3957884/22478615/3ffb9b22-e81d-11e6-88b6-a851aaf661f3.png)

Thanks.

**Comment by bulat-f** [comment]
Hi @greedmonkey . Just use in css something like this:

```css
.datepicker__input {
    border: 0 !important;
    border-bottom: .2rem solid !important;
    border-radius: 0 !important;
}
```
If you have this styles for other inputs already, you can override inline styles using `!important` there. For example:
```css
input {
    border-bottom: .2rem solid !important;
}
```
